// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDP3YwVLPZCdrkXftSrHzz_T9xncWmTfM',
    appId: '1:389377800962:web:36ffbc05be71e8fb70601b',
    messagingSenderId: '389377800962',
    projectId: 'fcm-squad-maker',
    authDomain: 'fcm-squad-maker.firebaseapp.com',
    databaseURL: 'https://fcm-squad-maker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-squad-maker.appspot.com',
    measurementId: 'G-76Z62YHZYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYWoM5yMw7RnUs_MOCQ31wILT1tQWYZ1I',
    appId: '1:389377800962:android:d4f6e9c9ab936af770601b',
    messagingSenderId: '389377800962',
    projectId: 'fcm-squad-maker',
    databaseURL: 'https://fcm-squad-maker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-squad-maker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8gbJ-L-WMbB9a2sNdfi1Z8lCJj_gJ-M',
    appId: '1:389377800962:ios:a203841390e3ad0070601b',
    messagingSenderId: '389377800962',
    projectId: 'fcm-squad-maker',
    databaseURL: 'https://fcm-squad-maker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-squad-maker.appspot.com',
    iosBundleId: 'com.quasar.fcmobileSquadMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC8gbJ-L-WMbB9a2sNdfi1Z8lCJj_gJ-M',
    appId: '1:389377800962:ios:a203841390e3ad0070601b',
    messagingSenderId: '389377800962',
    projectId: 'fcm-squad-maker',
    databaseURL: 'https://fcm-squad-maker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-squad-maker.appspot.com',
    iosBundleId: 'com.quasar.fcmobileSquadMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDP3YwVLPZCdrkXftSrHzz_T9xncWmTfM',
    appId: '1:389377800962:web:466b8f2cef2d020770601b',
    messagingSenderId: '389377800962',
    projectId: 'fcm-squad-maker',
    authDomain: 'fcm-squad-maker.firebaseapp.com',
    databaseURL: 'https://fcm-squad-maker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-squad-maker.appspot.com',
    measurementId: 'G-RPH3VFZ1LP',
  );
}
