name: fcmobile_squad_maker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  http:
  fluttertoast:
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.0
  firebase_database: ^11.0.2
  freezed_annotation:
  json_annotation: ^4.9.0
  gauge_indicator: ^0.4.3
  google_fonts:
  font_awesome_flutter:
  image_picker:
  graphic:
  marquee:
  provider:
  flutter_animate :
  rive:
  kakao_flutter_sdk_talk: ^1.9.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  freezed:
  json_serializable:
  flutter_native_splash:


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/field.png
    - assets/images/test_logo.png

  fonts:
    - family:  Custom_Icons
      fonts:
       - asset: assets/fonts/Custom_Icons.ttf

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.ttf
          weight: 900

